/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Administrator: typeof import('./src/components/Administrator.vue')['default']
    ButtonDelete: typeof import('./src/components/ButtonDelete.vue')['default']
    CardProject: typeof import('./src/components/CardProject.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCaretDown: typeof import('./src/components/icons/IconCaretDown.vue')['default']
    IconCaretDownSlim: typeof import('./src/components/icons/IconCaretDownSlim.vue')['default']
    IconClosePostSomething: typeof import('./src/components/icons/IconClosePostSomething.vue')['default']
    IconComment: typeof import('./src/components/icons/IconComment.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEmoji: typeof import('./src/components/icons/IconEmoji.vue')['default']
    IconEmojiPostSomething: typeof import('./src/components/icons/IconEmojiPostSomething.vue')['default']
    IconFacebook: typeof import('./src/components/icons/IconFacebook.vue')['default']
    IconFacebookBlue: typeof import('./src/components/icons/IconFacebookBlue.vue')['default']
    IconGIFPostSomething: typeof import('./src/components/icons/IconGIFPostSomething.vue')['default']
    IconGoogle: typeof import('./src/components/icons/IconGoogle.vue')['default']
    IconGoogleColor: typeof import('./src/components/icons/IconGoogleColor.vue')['default']
    IconImagePostSomething: typeof import('./src/components/icons/IconImagePostSomething.vue')['default']
    IconImgLogin: typeof import('./src/components/icons/IconImgLogin.vue')['default']
    IconLoadingPostsomething: typeof import('./src/components/icons/IconLoadingPostsomething.vue')['default']
    IconLogoSavvycom: typeof import('./src/components/icons/IconLogoSavvycom.vue')['default']
    IconMainComments: typeof import('./src/components/icons/IconMainComments.vue')['default']
    IconOptionPostStatus: typeof import('./src/components/icons/IconOptionPostStatus.vue')['default']
    IconPollingPostSomething: typeof import('./src/components/icons/IconPollingPostSomething.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconTwitter: typeof import('./src/components/icons/IconTwitter.vue')['default']
    IconTwitterColor: typeof import('./src/components/icons/IconTwitterColor.vue')['default']
    LoginToComment: typeof import('./src/components/LoginToComment.vue')['default']
    MainComments: typeof import('./src/components/MainComments.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PostSomething: typeof import('./src/components/PostSomething.vue')['default']
    PostStatus: typeof import('./src/components/PostStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollNotice: typeof import('./src/components/ScrollNotice.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SeeAll: typeof import('./src/components/SeeAll.vue')['default']
    SelectSort: typeof import('./src/components/SelectSort.vue')['default']
    SendMessage: typeof import('./src/components/SendMessage.vue')['default']
    ShowMoreComments: typeof import('./src/components/ShowMoreComments.vue')['default']
    SignWith: typeof import('./src/components/SignWith.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TotalComments: typeof import('./src/components/TotalComments.vue')['default']
    UserComment: typeof import('./src/components/UserComment.vue')['default']
    UserCommentWithoutFb: typeof import('./src/components/UserCommentWithoutFb.vue')['default']
    UsernameInput: typeof import('./src/components/UsernameInput.vue')['default']
    UserOption: typeof import('./src/components/UserOption.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
