server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: social-service
          uri: http://localhost:8082/
          predicates:
            - Path=/social/**
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user/**
jwt:
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1